# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'power.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1088, 936)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 211, 231))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(110, 190, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 190, 75, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(260, 20, 781, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 761, 251))
        self.textEdit.setObjectName("textEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 310, 781, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 20, 761, 271))
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 370, 211, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 260, 211, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(9, 30, 191, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 450, 201, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 500, 211, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_7)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 181, 131))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_11 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.comboBox_12 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboBox_13 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_13)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.comboBox_14 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_14)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.comboBox_15 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_15)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 160, 81, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 840, 191, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(260, 620, 781, 281))
        self.groupBox_8.setObjectName("groupBox_8")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 20, 761, 251))
        self.textEdit_3.setObjectName("textEdit_3")
        self.groupBox_10 = QtWidgets.QGroupBox(Form)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 710, 211, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 48, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_10)
        self.label_22.setGeometry(QtCore.QRect(10, 70, 72, 21))
        self.label_22.setObjectName("label_22")
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_16.setGeometry(QtCore.QRect(90, 29, 91, 21))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_11.setGeometry(QtCore.QRect(90, 60, 91, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 880, 191, 31))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "测试工具"))
        self.groupBox.setTitle(_translate("Form", "测试板串口设置"))
        self.label.setText(_translate("Form", "串口号"))
        self.comboBox.setItemText(0, _translate("Form", "COM1"))
        self.label_2.setText(_translate("Form", "波特率"))
        self.comboBox_2.setItemText(0, _translate("Form", "115200"))
        self.comboBox_2.setItemText(1, _translate("Form", "57600"))
        self.comboBox_2.setItemText(2, _translate("Form", "56000"))
        self.comboBox_2.setItemText(3, _translate("Form", "43000"))
        self.comboBox_2.setItemText(4, _translate("Form", "38400"))
        self.comboBox_2.setItemText(5, _translate("Form", "19200"))
        self.comboBox_2.setItemText(6, _translate("Form", "9600"))
        self.comboBox_2.setItemText(7, _translate("Form", "4800"))
        self.comboBox_2.setItemText(8, _translate("Form", "2400"))
        self.comboBox_2.setItemText(9, _translate("Form", "1200"))
        self.comboBox_2.setItemText(10, _translate("Form", "600"))
        self.comboBox_2.setItemText(11, _translate("Form", "300"))
        self.label_3.setText(_translate("Form", "数据位"))
        self.comboBox_3.setItemText(0, _translate("Form", "8"))
        self.comboBox_3.setItemText(1, _translate("Form", "7"))
        self.comboBox_3.setItemText(2, _translate("Form", "6"))
        self.label_4.setText(_translate("Form", "停止位"))
        self.comboBox_4.setItemText(0, _translate("Form", "1"))
        self.comboBox_4.setItemText(1, _translate("Form", "1.5"))
        self.comboBox_4.setItemText(2, _translate("Form", "2"))
        self.label_5.setText(_translate("Form", "校验位"))
        self.comboBox_5.setItemText(0, _translate("Form", "None"))
        self.comboBox_5.setItemText(1, _translate("Form", "Odd"))
        self.comboBox_5.setItemText(2, _translate("Form", "Even"))
        self.comboBox_5.setItemText(3, _translate("Form", "Mark"))
        self.comboBox_5.setItemText(4, _translate("Form", "Space"))
        self.pushButton.setText(_translate("Form", "打开串口"))
        self.pushButton_4.setText(_translate("Form", "串口初始化"))
        self.groupBox_2.setTitle(_translate("Form", "AD值"))
        self.groupBox_3.setTitle(_translate("Form", "电压值"))
        self.groupBox_4.setTitle(_translate("Form", "复位后再点击"))
        self.pushButton_2.setText(_translate("Form", "电压测试"))
        self.groupBox_5.setTitle(_translate("Form", "万用表设置"))
        self.label_8.setText(_translate("Form", "万用表IP"))
        self.lineEdit_3.setText(_translate("Form", "192.168.2.20"))
        self.label_9.setText(_translate("Form", "万用表端口号"))
        self.lineEdit_4.setText(_translate("Form", "5025"))
        self.pushButton_3.setText(_translate("Form", "清除接收区"))
        self.groupBox_7.setTitle(_translate("Form", "工具板串口设置"))
        self.label_13.setText(_translate("Form", "串口号"))
        self.comboBox_11.setItemText(0, _translate("Form", "COM1"))
        self.label_14.setText(_translate("Form", "波特率"))
        self.comboBox_12.setItemText(0, _translate("Form", "9600"))
        self.comboBox_12.setItemText(1, _translate("Form", "4800"))
        self.comboBox_12.setItemText(2, _translate("Form", "2400"))
        self.comboBox_12.setItemText(3, _translate("Form", "1200"))
        self.comboBox_12.setItemText(4, _translate("Form", "600"))
        self.comboBox_12.setItemText(5, _translate("Form", "300"))
        self.label_15.setText(_translate("Form", "数据位"))
        self.comboBox_13.setItemText(0, _translate("Form", "8"))
        self.comboBox_13.setItemText(1, _translate("Form", "7"))
        self.comboBox_13.setItemText(2, _translate("Form", "6"))
        self.label_16.setText(_translate("Form", "停止位"))
        self.comboBox_14.setItemText(0, _translate("Form", "1"))
        self.comboBox_14.setItemText(1, _translate("Form", "1.5"))
        self.comboBox_14.setItemText(2, _translate("Form", "2"))
        self.label_17.setText(_translate("Form", "校验位"))
        self.comboBox_15.setItemText(0, _translate("Form", "None"))
        self.comboBox_15.setItemText(1, _translate("Form", "Odd"))
        self.comboBox_15.setItemText(2, _translate("Form", "Even"))
        self.comboBox_15.setItemText(3, _translate("Form", "Mark"))
        self.comboBox_15.setItemText(4, _translate("Form", "Space"))
        self.pushButton_7.setText(_translate("Form", "打开串口"))
        self.pushButton_9.setText(_translate("Form", "大电流测试"))
        self.groupBox_8.setTitle(_translate("Form", "电流值"))
        self.groupBox_10.setTitle(_translate("Form", "恒压值设置"))
        self.label_21.setText(_translate("Form", "档位设置"))
        self.label_22.setText(_translate("Form", "档位设置按钮"))
        self.comboBox_16.setItemText(0, _translate("Form", "2"))
        self.comboBox_16.setItemText(1, _translate("Form", "3"))
        self.comboBox_16.setItemText(2, _translate("Form", "4"))
        self.comboBox_16.setItemText(3, _translate("Form", "5"))
        self.comboBox_16.setItemText(4, _translate("Form", "6"))
        self.comboBox_16.setItemText(5, _translate("Form", "7"))
        self.comboBox_16.setItemText(6, _translate("Form", "8"))
        self.comboBox_16.setItemText(7, _translate("Form", "9"))
        self.comboBox_16.setItemText(8, _translate("Form", "10"))
        self.pushButton_11.setText(_translate("Form", "设置"))
        self.pushButton_5.setText(_translate("Form", "小电流测试"))
